openapi: 3.0.0
info:
  description: 按照票据模版，归一化并自动分割医疗票据
  title: 票据分割 API
  version: 0.1.0
servers:
  - description: 内部测试地址
    url: http://localhost:5000/bill-segmentation
paths:
  /upload:
    post:
      operationId: upload_image
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadPayloadDto"
      responses:
        "200":
          content:
            application/json:
              example:
                imgId: eee0d217-598e-4987-82ff-3f4bb01570c8
                imgUrl: http://localhost:5000/static/eee0d217-598e-4987-82ff-3f4bb01570c8.jpg
              schema:
                $ref: "#/components/schemas/imgOnServerDto"
          description: OK
        "400":
          content:
            application/json:
              example:
                message: 图像文件格式不正确
              schema:
                $ref: "#/components/schemas/errorHandleDto"
          description: 图像文件格式不正确（后缀不正确）
      summary: 上载票据图像
      tags:
        - Basic
      x-openapi-router-controller: bill_segmentation.controllers.basic_controller
  /version:
    get:
      operationId: get_version
      responses:
        "200":
          content:
            application/json:
              example:
                version: bill-segmentation-v0.1.0
              schema:
                $ref: "#/components/schemas/versionDto"
          description: 返回版本号
      summary: 获取 API 版本号
      tags:
        - Version
      x-openapi-router-controller: bill_segmentation.controllers.version_controller
  /warp-perspective/{billTypeId}/{imgId}:
    post:
      operationId: warp_perspective
      parameters:
        - description: 票据类型 ID，用于唯一确定一个票据类型
          explode: false
          in: path
          name: billTypeId
          required: true
          schema:
            type: string
          style: simple
        - description: 票据图像 ID，用于唯一确定一个图像
          explode: false
          in: path
          name: imgId
          required: true
          schema:
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            example:
              pts:
                - x: 0
                  y: 0
                - x: 100
                  y: 0
                - x: 100
                  y: 100
                - x: 0
                  y: 100
            schema:
              $ref: "#/components/schemas/roiPtsDto"
      responses:
        "200":
          content:
            application/json:
              example:
                imgId: eee0d217-598e-4987-82ff-3f4bb01570c8.perspective
                imgUrl: http://localhost:5000/static/eee0d217-598e-4987-82ff-3f4bb01570c8.perspective.jpg
              schema:
                $ref: "#/components/schemas/imgOnServerDto"
          description: OK
        "400":
          content:
            application/json:
              examples:
                图像 ID 不正确:
                  value:
                    message: 要求矫正的图像不存在
                票据类型不正确:
                  value:
                    message: 票据库中没有该票据类型
              schema:
                $ref: "#/components/schemas/errorHandleDto"
          description: 票据类型或票据 ID 不正确
      summary: 对图像进行透视矫正
      tags:
        - Image Process
      x-openapi-router-controller: bill_segmentation.controllers.image_process_controller
  /warp-segmentation/{billTypeId}/{imgId}:
    get:
      operationId: warp_segmentation
      parameters:
        - description: 票据类型 ID，用于唯一确定一个票据类型
          explode: false
          in: path
          name: billTypeId
          required: true
          schema:
            type: string
          style: simple
        - description: 票据图像 ID，用于唯一确定一个图像
          explode: false
          in: path
          name: imgId
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/billSegmentationDto"
          description: OK
        "400":
          content:
            application/json:
              examples:
                图像 ID 不正确:
                  value:
                    message: 要求分割的图像不存在
                票据类型不正确:
                  value:
                    message: 票据库中没有该票据类型
              schema:
                $ref: "#/components/schemas/errorHandleDto"
          description: 票据类型或票据 ID 不正确
      summary: 分割指定图像
      tags:
        - Image Process
      x-openapi-router-controller: bill_segmentation.controllers.image_process_controller
components:
  parameters:
    billTypeId:
      description: 票据类型 ID，用于唯一确定一个票据类型
      explode: false
      in: path
      name: billTypeId
      required: true
      schema:
        type: string
      style: simple
    imgId:
      description: 票据图像 ID，用于唯一确定一个图像
      explode: false
      in: path
      name: imgId
      required: true
      schema:
        type: string
      style: simple
  schemas:
    errorHandleDto:
      properties:
        message:
          title: message
          type: string
      title: errorHandleDto
      type: object
    versionDto:
      example:
        version: version
      properties:
        version:
          title: version
          type: string
      title: versionDto
      type: object
    uploadPayloadDto:
      properties:
        file:
          format: binary
          type: string
      type: object
    imgOnServerDto:
      example:
        imgUrl: imgUrl
        imgId: imgId
      properties:
        imgId:
          description: 图像 ID，用于唯一确定一个图像
          title: imgId
          type: string
        imgUrl:
          description: 图像 Url，用于访问图像
          title: imgUrl
          type: string
      title: imgOnServerDto
      type: object
    roiPtsDto:
      properties:
        pts:
          items:
            $ref: "#/components/schemas/roiPtsDto_pts"
          maxItems: 4
          minItems: 4
          type: array
      type: object
    billSegmentationDto:
      items:
        properties:
          name:
            description: 图像片段的名称，例如：姓名、性别等
            type: string
          imgUrl:
            description: 图像 Url，用于访问图像
            type: string
        type: object
      type: array
    roiPtsDto_pts:
      properties:
        x:
          title: x
          type: integer
        y:
          title: "y"
          type: integer
      title: roiPtsDto_pts
      type: object
